### ISSUE TITLE
Unity 2022.3 errors

### ISSUE THREAD

**Issue by justinwasilenko** [nukadelic/unity-application-spacewarp#6]
Trying to load the project into Unity 2022.3.16f1 I get the following errors on startup:

> Library\PackageCache\com.unity.visualeffectgraph@70f6ba3716\Editor\GraphView\BoundsRecorder\VFXBoundsRecorder.cs(312,48): error CS1061: 'VisualEffect' does not contain a definition for 'GetCurrentPadding' and no accessible extension method 'GetCurrentPadding' accepting a first argument of type 'VisualEffect' could be found (are you missing a using directive or an assembly reference?)

> Library\PackageCache\com.unity.visualeffectgraph@70f6ba3716\Editor\Compiler\VFXGraphCompiledData.cs(1199,238): error CS1503: Argument 10: cannot convert from 'uint' to 'UnityEngine.VFX.VFXInstancingDisabledReason'

Not sure if 2022.3 is supported, or even if Spacewarp is still being supported. But I hoped to use it in a future project using Unity 2022.3, or 2023, and luckily found this repo to at least see it in action.

**Comment by nukadelic** [comment]
~~Tried on few unity versions don't remember having this problem on 22.3 , might be an editor version conflict , but try remove the custom vfx graph package and replace it with the default one , spacewarp logic is done on the urp package and shader graph so it should be pretty straight forward to make a new shader graph with vfx graph as the target and use a custom shader in your visual effects graph.~~

Edit : created a `2022.3` [branch ](https://github.com/nukadelic/unity-application-spacewarp/tree/2023.2)to support URP v16

**Comment by getElementsByClassName** [comment]
Hi
I'm trying to run your sample project in Unity version 2023.2.6f1, however, I'm getting this error (whenever I try a build). Is that something that has occurred to you?
Thanks!

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.RenderPipelineGraphicsSettingsStripper.PerformStripping (System.Collections.Generic.List`1[T] settingsList, System.Collections.Generic.List`1[T] runtimeSettingsList) (at ./Packages/com.unity.render-pipelines.core/Runtime/Stripping/RenderPipelineGraphicsSettingsStripper.cs:54)
UnityEngine.Rendering.RenderPipelineGraphicsSettingsContainer.OnBeforeSerialize () (at ./Packages/com.unity.render-pipelines.core/Runtime/RenderPipeline/RenderPipelineGraphicsSettingsContainer.cs:45)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by nukadelic** [comment]
[https://github.com/nukadelic/unity-application-spacewarp/tree/2023.2](https://github.com/nukadelic/unity-application-spacewarp/tree/2023.2) did you try this one ?

**Comment by getElementsByClassName** [comment]
Yes.
And the error happens on 'Build and Run' (2023.2.6f1)

**Comment by nukadelic** [comment]
Are you sure you are using the `2023.2` branch ? 
I just cloned the 2023.2 branch and Build it using `2023.2.0b10` (beta) , installed it and run it on my Quest 2 without issues , can confirm my experimental branch works on that unity version. Didn't test on your version specifically , ill try testing with `2023.2.6f1` a bit later but it should work as well ( that branch has URP version 16 in it ) 

Here is the build apk : https://www.mediafire.com/file/xmb0jremtsecqjy/BUILD.apk/file

**Comment by nukadelic** [comment]
updated to 16.0.6 give it a shot : https://github.com/nukadelic/unity-application-spacewarp/tree/2023.216.0.6
