### ISSUE TITLE
Old URP Package

### ISSUE THREAD

**Issue by davoodkharmanzar** [nukadelic/unity-application-spacewarp#9]
hey,

does a plan to update spacewarp-urp packages? [URP 16.0.6]

thanks.

**Comment by nukadelic** [comment]
There is " 16.0.3 " - [here](https://github.com/nukadelic/unity-application-spacewarp/tree/2023.2) - or do you want the exact 0.6 version ?

**Comment by davoodkharmanzar** [comment]
yup ...
i'm using that ...

but would be better if upgrade to 16.0.6 or 16.0.5 to better compatible with the latest 2023.2.x series and latest Meta Packages. => https://npm.developer.oculus.com/
thanks.

**Comment by nukadelic** [comment]
I see , will try merge the changes to a newer version version. If ill get it done - would you add the minimal necessary meta packages and do a merge request ?

**Comment by nukadelic** [comment]
Try this https://github.com/nukadelic/unity-application-spacewarp/tree/2023.216.0.6
